name: precvisao
description: A Flutter app to check weather forecast

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/weather_data.json
